global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PDF2MD 애플리케이션 모니터링 (Node.js 메트릭)
  - job_name: 'pdf2md-app'
    static_configs:
      - targets: ['pdf2md:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # Nginx 모니터링 (nginx-prometheus-exporter 필요)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s

  # 시스템 메트릭 (node_exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s

  # Docker 컨테이너 메트릭 (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 30s

# 알림 규칙 (선택사항)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 원격 저장소 설정 (선택사항)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "username"
#       password: "password" 